apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: itdt-contained-frontend
          image: ifilyaninitmo/itdt-contained-frontend:master
          ports:
          - name: container-port
            containerPort: 3000
          env:
            - name: REACT_APP_USERNAME
              value: "DG-GDST"
            - name: REACT_APP_COMPANY_NAME
              value: "ITMO"

---

apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
    type: NodePort
    ports:
    - port: 8200
      targetPort: container-port
    selector:
      app: app
      